characters = {
    '!': 'EXCLAM',
    '(': 'LPAR',
    ')': 'RPAR',
    '[': 'LSQB',
    ']': 'RSQB',
    '{': 'LBRACE',
    '}': 'RBRACE',
    ':': 'COLON',
    ';': 'SEMICOLON',
    ',': 'COMMA',
    '+': 'PLUS',
    '-': 'MINUS',
    '*': 'STAR',
    '/': 'SLASH',
    '|': 'VBAR',
    '&': 'AMPER',
    '<': 'LESS',
    '>': 'GREATER',
    '=': 'EQUAL',
    '.': 'DOT',
    '%': 'PERCENT',
    '==': 'EQEQUAL',
    '!=': 'NOTEQUAL',
    '<=': 'LESSEQUAL',
    '>=': 'GREATEREQUAL',
    '~': 'TILDE',
    '^': 'CIRCUMFLEX',
    '<<': 'LEFTSHIFT',
    '>>': 'RIGHTSHIFT',
    '**': 'DOUBLESTAR',
    '+=': 'PLUSEQUAL',
    '-=': 'MINEQUAL',
    '*=': 'STAREQUAL',
    '/=': 'SLASHEQUAL',
    '%=': 'PERCENTEQUAL',
    '&=': 'AMPEREQUAL',
    '&&': 'DAMPER',
    '|=': 'VBAREQUAL',
    '^=': 'CIRCUMFLEXEQUAL',
    '||': 'DVBAR',
    '<<=': 'LEFTSHIFTEQUAL',
    '>>=': 'RIGHTSHIFTEQUAL',
    '**=': 'DOUBLESTAREQUAL',
    '//': 'DOUBLESLASH',
    '//=': 'DOUBLESLASHEQUAL',
    '===': 'IS',
    '!==': 'NOTIS',

    '...': 'ELLIPSIS',
    '#': 'COMMENT',
    '\n': 'NEWLINE'
}

special_characters = set(list(''.join(characters.keys())))
