from core.objects.characters import characters


NO_TYPE = 'NO_TYPE'
INTEGER = 'INTEGER'
FLOAT = 'FLOAT'
STRING = 'STRING'
BOOL = 'BOOL'
VARIABLE = 'VARIABLE'
OPERATOR = 'OPERATOR'

FUNCTION = 'FUNCTION'
FUNCTION_CALL = 'FUNCTION_CALL'
VARASSIGN = 'VARASSIGN'
RETURN_STATEMENT = 'RETURN_STATEMENT'
BREAK_STATEMENT = 'BREAK_STATEMENT'
CONTINUE_STATEMENT = 'CONTINUE_STATEMENT'
EXPR = 'EXPR'   # function calls, math operations, etc.
IF_BLOCK = 'IF_BLOCK'
ELIF_BLOCK = 'ELIF_BLOCK'
ELSE_BLOCK = 'ELSE_BLOCK'
CONDITION_BRANCH = 'CONDITION_BRANCH'   # summary for 3 previous class-types

PARENTHESIS = 'PARENTHESIS'  # common name
BRACES = 'BRACES'    # ()
FBRACES = 'FBRACES'  # {}
QBRACES = 'QBRACES'  # []

NEWLINE = characters['\n']
DOT = characters['.']
COMMA = characters[',']
COLON = characters[':']
EQUALS = characters['=']
ANY = 'ANY'
